[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ms_model"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = ["numpy", "torch", "wandb", "pyyaml", "opencv-python"]

[project.optional-dependencies]
dev = ["pytest"]
demo = ["gradio"]

[tool.setuptools.packages.find]
include = ["ms_model*"]
