_wandb:
    value:
        cli_version: 0.27.2
        e:
            thu3bhcqkog6es5flqn9ptnbody5m9a9:
                args:
                    - --config
                    - configs/evimo_smoke.yaml
                    - --wandb-name
                    - evimo-smoke
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "107321753600"
                        used: "13772058624"
                email: arthur.ouf9@gmail.com
                executable: /home/i/i0002573/miniconda3/envs/devo/bin/python
                git:
                    commit: 8d5f32600d3d8faf4d4b9806d679c0c1dad48b3e
                    remote: https://github.com/arthurfou/MS_Model.git
                gpu: NVIDIA A100-PCIE-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-551e8f12-f2dd-dd64-4aa7-fd7b2b004278
                host: xgpg5
                memory:
                    total: "270278537216"
                os: Linux-6.8.0-124-generic-x86_64-with-glibc2.39
                program: -m ms_model.training.train
                python: CPython 3.10.0
                root: /home/i/i0002573/arthur_ipal/MS_Model
                slurm:
                    cluster_name: soc
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: allusers
                    job_cpus_per_node: "8"
                    job_end_time: "1782534537"
                    job_gid: "9130"
                    job_gpus: "0"
                    job_id: "642329"
                    job_name: ms_model
                    job_nodelist: xgpg5
                    job_num_nodes: "1"
                    job_partition: gpu-long
                    job_qos: normal
                    job_start_time: "1782275337"
                    job_uid: "58796"
                    job_user: i0002573
                    jobid: "642329"
                    localid: "0"
                    mem_per_node: "32768"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: xgpg5
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /home/i/i0002573/arthur_ipal/MS_Model
                    submit_host: xgpe5
                    task_pid: "704999"
                    tasks_per_node: "1"
                    topology_addr: xgpg5
                    topology_addr_pattern: node
                    tres_per_task: cpu=8
                startedAt: "2026-06-24T04:29:28.632992Z"
                writerId: thu3bhcqkog6es5flqn9ptnbody5m9a9
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.0
            "5": 0.27.2
            "12": 0.27.2
            "13": linux-x86_64
data:
    value:
        max_objects: 3
        n_slices_context: 5
        root: ../datasets/EV-IMO/eval
        slice_dt: 0.025
        train_sequences:
            - box/npz/seq_00.npz
        val_sequences:
            - tabletop/npz/seq_00.npz
model:
    value:
        H: 260
        W: 346
        ecn_variant: shallow
        max_objects: 3
        n_context_slices: 5
        name: evimo
training:
    value:
        batch_size: 2
        checkpoint_dir: checkpoints
        epochs: 2
        evimo_loss_kwargs:
            w_depth: 1
            w_mask: 0.5
        lr: 0.01
        num_workers: 0
wandb:
    value:
        entity: arthurfou-cole-polytechnique
        name: evimo-smoke
        project: ms-model
