data:
  root: ../EVOwithMS/datasets/EV-IMO/eval
  train_sequences:
    - box/npz/seq_00.npz
  val_sequences:
    - box/npz/seq_01.npz
  seq_len: 16
  nb_time_bins: 5
  patch_size: 4
  mask_thicken_radius: 3

model:
  name: convlstm
  hidden_dim: 32

training:
  epochs: 2
  batch_size: 2
  lr: 1.0e-3
  loss: bce
  num_workers: 0
  checkpoint_dir: checkpoints

wandb:
  project: ms-model
  entity: arthurfou-cole-polytechnique
  name: ""  # vide = nom auto-genere par wandb (ex: "swept-breeze-2")
