_wandb:
    value:
        cli_version: 0.27.2
        e:
            l7364mypcggpx0pfvwbxh7wjtmqpjmvd:
                args:
                    - --config
                    - configs/evimo_model_long.yaml
                    - --wandb-name
                    - evimo-baseline-long
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "99950723072"
                        used: "9358802944"
                email: arthur.ouf9@gmail.com
                executable: /home/i/i0002573/miniconda3/envs/devo/bin/python
                git:
                    commit: 8d5f32600d3d8faf4d4b9806d679c0c1dad48b3e
                    remote: https://github.com/arthurfou/MS_Model.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-d5994002-15eb-bf54-2ead-39872e30e4f6
                host: xgph11
                memory:
                    total: "270078832640"
                os: Linux-6.8.0-124-generic-x86_64-with-glibc2.39
                program: -m ms_model.training.train
                python: CPython 3.10.0
                root: /home/i/i0002573/arthur_ipal/MS_Model
                slurm:
                    cluster_name: soc
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: allusers
                    job_cpus_per_node: "8"
                    job_end_time: "1782541311"
                    job_gid: "9130"
                    job_gpus: "0"
                    job_id: "642418"
                    job_name: ms_model
                    job_nodelist: xgph11
                    job_num_nodes: "1"
                    job_partition: gpu-long
                    job_qos: normal
                    job_start_time: "1782282111"
                    job_uid: "58796"
                    job_user: i0002573
                    jobid: "642418"
                    localid: "0"
                    mem_per_node: "32768"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: xgph11
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /home/i/i0002573/arthur_ipal/MS_Model
                    submit_host: xgpe5
                    task_pid: "527450"
                    tasks_per_node: "1"
                    topology_addr: xgph11
                    topology_addr_pattern: node
                    tres_per_task: cpu=8
                startedAt: "2026-06-24T06:22:35.582376Z"
                writerId: l7364mypcggpx0pfvwbxh7wjtmqpjmvd
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.0
            "5": 0.27.2
            "12": 0.27.2
            "13": linux-x86_64
data:
    value:
        max_objects: 3
        n_slices_context: 5
        root: ../datasets/EV-IMO/eval
        slice_dt: 0.025
        train_sequences:
            - box/npz/seq_00.npz
            - box/npz/seq_01.npz
            - box/npz/seq_02.npz
            - box/npz/seq_03.npz
            - box/npz/seq_04.npz
            - box/npz/seq_05.npz
            - fast/npz/seq_00.npz
            - fast/npz/seq_01.npz
            - wall/npz/seq_00.npz
            - wall/npz/seq_01.npz
        val_sequences:
            - tabletop/npz/seq_00.npz
            - tabletop/npz/seq_01.npz
model:
    value:
        H: 260
        W: 346
        ecn_variant: baseline
        max_objects: 3
        n_context_slices: 5
        name: evimo
training:
    value:
        batch_size: 8
        checkpoint_dir: checkpoints
        epochs: 100
        evimo_loss_kwargs:
            depth_loss_kwargs:
                lambda_smooth: 0.1
            mask_loss_kwargs:
                lambda_bce: 1
                lambda_smooth: 0.1
            w_depth: 1
            w_mask: 0.5
            warp_loss_kwargs:
                use_fine_loss: false
        lr: 0.01
        num_workers: 4
wandb:
    value:
        entity: arthurfou-cole-polytechnique
        name: ""
        project: ms-model
